//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Neva_Svyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID_address { get; set; }
        public int ID_district { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string building { get; set; }
        public int flat { get; set; }
        public Nullable<int> room { get; set; }
        public int ID_subscriber { get; set; }
    
        public virtual District District { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
