//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Neva_Svyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ID_contract { get; set; }
        public string Contract_Number { get; set; }
        public System.DateTime Conclusion_date { get; set; }
        public Nullable<System.DateTime> Termination_date { get; set; }
        public Nullable<System.DateTime> Termination_reason { get; set; }
        public int ID_subscriber { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
    }
}
