//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Neva_Svyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int ID_Events { get; set; }
        public string Title { get; set; }
        public System.DateTime Time { get; set; }
        public int ID_role { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
