//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Neva_Svyaz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Telecom_Neva_SvyazEntities1 : DbContext
    {
        public Telecom_Neva_SvyazEntities1()
            : base("name=Telecom_Neva_SvyazEntities1")
        {
        }

        private static Telecom_Neva_SvyazEntities1 context;
        public static Telecom_Neva_SvyazEntities1 GetContext()
        {
            if (context == null)
                context = new Telecom_Neva_SvyazEntities1();

            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Development_type> Development_type { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Equipment_type> Equipment_type { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<Problem> Problem { get; set; }
        public virtual DbSet<Rent> Rent { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Service_kind> Service_kind { get; set; }
        public virtual DbSet<Service_type> Service_type { get; set; }
        public virtual DbSet<Subscriber> Subscriber { get; set; }
        public virtual DbSet<Support> Support { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
