//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Neva_Svyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int ID_rent { get; set; }
        public int Contract_number { get; set; }
        public string Payment_terms { get; set; }
        public int ID_subscriber { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
    }
}
