//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Neva_Svyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID_request { get; set; }
        public string Request_number { get; set; }
        public int ID_service { get; set; }
        public int ID_problem { get; set; }
        public System.DateTime Creation_date { get; set; }
        public Nullable<System.DateTime> Closing_date { get; set; }
        public string Status { get; set; }
        public string Discription { get; set; }
        public int ID_subscriber { get; set; }
        public int ID_equipment { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Problem Problem { get; set; }
        public virtual Service Service { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
