//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Neva_Svyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int ID_support { get; set; }
        public int ID_subscriber { get; set; }
        public System.DateTime Application_data { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
    }
}
